<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Task Role Mapping_ui-igdialog-close-ic_35be36</name>
   <tag></tag>
   <elementGuidId>07133000-5159-4cd4-b008-c43632ed0672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mapdialog']/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igdialog-close-icon ui-icon ui-icon-close</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mapdialog&quot;)/div[@class=&quot;ui-igdialog-header ui-dialog-titlebar ui-widget-header ui-corner-top ui-helper-clearfix ui-draggable-handle&quot;]/a[@class=&quot;ui-igdialog-headerbutton ui-corner-all ui-state-default ui-igdialog-buttonclose ui-igdialog-headerbutton-hover ui-state-hover&quot;]/span[@class=&quot;ui-igdialog-close-icon ui-icon ui-icon-close&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mapdialog']/div/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/a/span</value>
   </webElementXpaths>
</WebElementEntity>
